<?php
define("IN_IBB", 1);

$root_path = "../";

if(file_exists("../includes/config.php"))
{
	include("../includes/config.php");


	// Unset db config because we dont need it!
	if(isset($database_config))
	{
	        unset($database_config);
	}

	// Check if the forum is already installed
	if(defined("INSTALLED") && INSTALLED == 1)
	{
	        header("Location: ../");
	        exit();
	}
}

error_reporting(E_ALL);

require_once($root_path . "classes/csrf.php");
require_once($root_path . "includes/rendering.php");
require_once($root_path . "classes/template.php");
require_once($root_path . "language/english/install.php");

Template::setBasePath($root_path . "templates/original/install");
$template_vars = array(
	"TEMPLATE_PATH" => $root_path . "templates/original"
);
Template::addNamespace("T", $template_vars);
Template::addNamespace("L", $lang);

if(!isset($_POST['Submit']))
{

// Attempt to guess the directory
if(!empty($_ENV['SERVER_NAME']) || !empty($_SERVER['SERVER_NAME']))
{
	$server_name = (!empty($HTTP_SERVER_VARS['SERVER_NAME'])) ? $HTTP_SERVER_VARS['SERVER_NAME'] : $HTTP_ENV_VARS['SERVER_NAME'];
}
else if(!empty($_ENV['HTTP_HOST']) || !empty($_SERVER['HTTP_HOST']))
{
	$server_name = (!empty($HTTP_SERVER_VARS['HTTP_HOST'])) ? $HTTP_SERVER_VARS['HTTP_HOST'] : $HTTP_ENV_VARS['HTTP_HOST'];
}
else
{
	$server_name = "";
}
$script_path = (isset($_ENV['PHP_SELF']) && !empty($_ENV['PHP_SELF'])) ? $_ENV['PHP_SELF'] : $_SERVER['PHP_SELF'];

$path = "http://" . $server_name . $script_path;
preg_match("#^(.*)/install/(.*)\$#", $path, $directory);
$directory = $directory[1];

//page_header();

$page_master = new Template("install.tpl");
		$page_master->setVars(array(
			"CSRF_TOKEN" => CSRF::getHTML(),
			"DIRECTORY" => $directory
		));

		outputPage($page_master, $directory);

//page_footer();

}
else
{

page_header();

echo <<<END
					<table width="90%" align="center" class="maintable">
						<tr>
							<th colspan="2" height="25">Installing..</th>
						</tr>
						<tr>
							<td class="cell2">
END;


if($_POST['useftp'] == "true")
{
	include("temp_ftp.php");
	echo "Connecting to FTP server...  ";
	$ftp = new ftp($_POST['ftpuser'], $_POST['ftppass']);

	if(!$ftp->chdir($_POST['ftppath']))
	{
		error_msg("FTP directory is invalid... Exiting");
	}

	echo "Done<br /><br />";
}
$dbhost = $_POST['dbhost'];
$dbuser = $_POST['dbuser'];
$dbpass = $_POST['dbpass'];
$dbname = $_POST['dbname'];
$dbtype = $_POST['dbtype'];

$file_data = <<<END
<?php

/*======================================================================*\
|| #################################################################### ||
|| #  				  Imperial Bulletin Board v2.x                    # ||
|| # ---------------------------------------------------------------- # ||
|| #  For licence, version amd changelog questions or concerns,       # ||
|| #  navigate to the docs/ folder or visit the forums at the		  # ||
|| #  website, http://www.imperialbb.com/forums. with your questions. # ||
|| # ---------------------------------------------------------------- # ||
|| # Name: config.php                                                 # ||
|| # ---------------------------------------------------------------- # ||
|| #                 "Copyright © 2006 M-ka Network"                  # ||
|| # ---------------------------------------------------------------- # ||
|| #################################################################### ||
\*======================================================================*/

if(!defined("IN_IBB")) {
	die("Hacking Attempt");
}

// This file is automatically generated by the ImperialBB installer
// Only edit this file if you know what your doing
\$database = array(
	'dbhost' => '$dbhost',
	'dbuser' => '$dbuser',
	'dbpass' => '$dbpass',
	'dbname' => '$dbname',
	'dbtype' => '$dbtype',
	'dbpcon' => 'n',
	'prefix' => 'ibb_'
);

\$db_prefix = \$database['prefix'];

\$debug = 0; // Debug mode (2 = advanced, 1 = simple, 0 = off)

##### There is no need to edit anything beyond here #####
define("INSTALLED", 1);

/*======================================================================*\
|| #################################################################### ||
|| #                 "Copyright © 2006 M-ka Network"                  # ||
|| #################################################################### ||
\*======================================================================*/
?>
END;

$db = mysql_connect($_POST['dbhost'], $_POST['dbuser'], $_POST['dbpass']) or error_msg("Could not connect to mysql database:<br />".mysql_error());

if(!mysql_select_db($_POST['dbname'],$db))
{
	error_msg("Unable to select mysql database, please ensure it already exists");
}

echo "Running SQL queries...  ";
$file_content = file("database.sql");
$query = "";
foreach($file_content as $sql_line)
{
	$trimmed = trim($sql_line);
	if (($sql_line != "") && (substr($trimmed, 0, 2) != "--") && (substr($trimmed, 0, 1) != "#"))
	{
		$query .= $sql_line;
		if(preg_match("/;\s*$/", $sql_line))
		{
			if (!mysql_query($query)) {
				echo "<b>Error</b><br />SQL : $query<br />Error : " . mysql_error();
			}
			$query = "";
		}
	}
}

if(!mysql_query("INSERT INTO `ibb_users` (`username`, `user_password`, `user_email`, `user_date_joined`, `user_level`, `user_rank`) VALUES ('".$_POST['admin_user']."', '".md5(md5($_POST['admin_pass']))."', '".$_POST['admin_email']."', '".time()."', '5', '3')"))
{
	echo "<b>Error</b> : #1 Unable to insert admin user : " . mysql_error() . "<br />";
}

if(!mysql_query("UPDATE `ibb_config` SET `config_value` = '" . $_POST['forum_name'] . "' WHERE `config_name` = 'site_name'"))
{
	echo "<b>Error</b> : #5 Unable to update mysql data : " . mysql_error() . "<br />";
}
if(!mysql_query("UPDATE `ibb_config` SET `config_value` = '" . $_POST['forum_desc'] . "' WHERE `config_name` = 'site_desc'"))
{
	echo "<b>Error</b> : #6 Unable to update mysql data : " . mysql_error() . "<br />";
}
if(!mysql_query("UPDATE `ibb_config` SET `config_value` = '" . $_POST['forum_path'] . "' WHERE `config_name` = 'url'"))
{
	echo "<b>Error</b> : #7 Unable to update mysql data : " . mysql_error() . "<br />";
}

echo "Done<br /><br />";

echo "<b>Configuration File</b><br /><br />Please upload the below file contents into includes/config.php<br /><textarea rows=\"20\" cols=\"75\">".htmlspecialchars($file_data)."</textarea>";

echo <<<END
							<br /><br /><h2>Forum Installed Successfully</h2><br />You may now continue to your board by <a href="../">Clicking Here</a>
							</td>
						</tr>
					</table>
END;

page_footer();

}

function page_header()
{

	echo <<<END
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
<head>
 <title>ImperialBB Forum Software Installer</title>
 <link rel="stylesheet" type="text/css" href="tpl_files/style.css" />
 <script type="text/javascript" src="tpl_files/scripts.js"></script>
</head>
<body bgcolor="#E5E5E5">
<table width="100%" align="center" class="bodytable">
	<tr>
		<td>
			<table width="98%" align="center">
				<tr>
					<td style="border-style: solid; border-color: #1E34FD; border-width: 1px; padding: 1px;">
						<table width="100%" cellpadding="0" cellspacing="0">
							<tr>
								<td height="67" width="256" align="left">
									<img src="tpl_files/logo.gif" />
								</td>
								<td>
									<img src="tpl_files/logo2.gif" height="67" width="100%" />
								</td>
							</tr>
						</table>
					</td>
				</tr>
				<tr>
					<td>
					<br /><br />
END;

}

function page_footer()
{

	echo <<<END
					</td>
				</tr>
			</table>
			<br />
		</td>
	</tr>
</table>
<br />
<table align="center" cellpadding="0" cellspacing="0">
	<tr>
		<td align="center">
			Powered by <a href="http://www.imperialbb.com/">ImperialBB</a><br />
		</td>
	</tr>
</table>
</body>
</html>
END;

}

function error_msg($message)
{
	echo <<<END
							$message
							<br /><br /><h2>Failed to install forum</h2>
							</td>
						</tr>
					</table>
END;
	page_footer();
	exit();
}


?>
